// 쇼츠 영상 10가지 컨셉 프리셋.
// 사용자가 컨셉을 고르면 영상 추가 지시(extra)에 컨셉 설명이 자동 반영되고,
// 가능한 경우 어울리는 프리셋 아바타도 추천한다.
// preferredAvatarIds 가 1개면 솔로 컨셉, 2개 이상이면 멀티 아바타 컨셉.
// useStandardEndpoint: true 이면 솔로여도 /v2/video/generate 로 만든다 ($1/분, 자동 연출 X).
// sceneAvatarIds (선택): 같은 인물의 HeyGen Photo Avatar variant 들을 씬마다 순환시킨다.
//   - 솔로 컨셉(preferredAvatarIds 1개) 위에 얹는 옵션이라 useMultiAvatar 분기는 타지 않는다.
//   - 씬 수가 배열 길이보다 많으면 mod 순환.
//   - 정의되지 않으면 preferredAvatarIds[0] 만 사용 (기존 동작).
// randomVariantPerVideo (선택, sceneAvatarIds 와 함께만 의미 있음):
//   - true 면 영상 1개를 만들 때 sceneAvatarIds 중 1개를 랜덤으로 뽑아 모든 씬에 동일 적용한다.
//     → 한 영상 안에서는 같은 배경, 영상마다 배경이 달라짐 (dongwan_secret 처럼 "같은 방" 가이드용).
//   - false/생략이면 기본 동작(씬마다 mod 순환).
// shuffleSceneVariants (선택, sceneAvatarIds 와 함께만 의미 있음):
//   - true 면 영상 1개를 만들 때마다 sceneAvatarIds 풀을 랜덤 셔플해 씬마다 서로 다른 variant 를 쓴다.
//     → 같은 인물의 여러 룩이 한 영상에서 순환, 영상마다 룩 조합이 달라짐 (godsaeng_routine 브이로그 흐름용).
//   - randomVariantPerVideo 와 동시에 true 면 randomVariantPerVideo 가 우선한다.
// backgroundColor (선택): 지정 시 layout 배경이 없는 모든 씬에 해당 단색 배경을 깐다.
//   - 아바타가 9:16 프레임을 못 채울 때 여백을 일관된 색으로 메워 프레이밍을 통일하는 용도 (study_dialogue).
// hiddenFromUI (선택): true 면 SHORTS_VIDEO_CONCEPT_OPTIONS(UI 컨셉 선택 목록)에서 제외된다.
//   - 컨셉 정의 자체는 남아 findShortsVideoConcept·테스트 스크립트에서는 계속 동작한다.
// testScript 는 컨셉 테스트용 약 15초 분량 대본.
// 아바타 ID 는 heygenAvatars.js 의 단일 진실 소스(HEYGEN_AVATAR_IDS) 에서만 참조한다.
// (단 sceneAvatarIds 는 같은 인물의 variant 라 raw 문자열로 작성한다.)

import { HEYGEN_AVATAR_IDS } from './heygenAvatars'

export const SHORTS_VIDEO_CONCEPTS = [
  {
    id: 'briefing_dongwan',
    label: '동완쌤 1퍼센트 입시 데이터 브리핑',
    summary: '공신력 있는 통계로 입시 정책 변화를 분석',
    direction: [
      '신뢰감 있는 정장 차림과 전문적인 말투. 채널 권위 강화에 초점.',
      '인트로(씬 1) · 아웃트로(마지막 씬) 는 동완쌤 풀화면 — 화면 텍스트 오버레이·키워드 카드 없이 아바타만 깔끔하게.',
      '중간 데이터 씬은 HeyGen AI 가 생성하는 풀화면 인포그래픽 화면으로 전환 — 아바타는 화면에 노출하지 않고 보이스오버만 깔린다. 차트·숫자·키워드 같은 시각 요소는 우리가 따로 그리지 않고 HeyGen 의 장면 생성에 맡긴다 (visualDescription 으로 지시).',
      'PIP·좌상단 작은 아바타 합성 금지.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.dongwan_ssaem],
    // 인포그래픽 씬을 HeyGen 자체 AI 가 직접 그리도록 Video Agent (/v1/video_agent/generate)
    // 경로 사용. 표준 엔드포인트($1/분) 대신 $2/분 — 자연어 프롬프트로 인포그래픽 시각화·아바타 미노출 등 직접 지시.
    testScript: {
      title: '의대 선호도 1퍼센트의 진실',
      duration: '15',
      hook: '의대 입시의 비밀, 데이터로 보여드립니다.',
      scenes: [
        { sceneNumber: 1, duration: '3', layout: 'full', noTextOverlay: true,
          narration: '안녕하세요, 동완쌤입니다. 오늘은 의대 입시 데이터를 풀어드릴게요.',
          visualDescription: 'Full-frame avatar in a clean studio with navy backdrop and subtle gold accent' },
        { sceneNumber: 2, duration: '3', layout: 'infographic-full',
          narration: '의대 선호도가 작년 대비 12.4퍼센트 상승했습니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, navy backdrop with subtle gold accent matching the briefing series, headline "의대 선호도" at the top, a large bold "+12.4%" centered as the hero statistic, a clean ascending bar chart below the number, small subtitle "작년 대비 상승", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '의대 선호도 +12.4%' },
        { sceneNumber: 3, duration: '3', layout: 'infographic-full',
          narration: '상위 1퍼센트 중 절반이 의대를 선택합니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, same navy + gold briefing-series palette, headline "상위 1%" at the top, a large bold "50%" centered as the hero statistic, a clean pie chart split exactly in half below the number, small subtitle "의대 선택", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '상위 1% 중 의대 50%' },
        { sceneNumber: 4, duration: '3', layout: 'infographic-full',
          narration: '정원은 그대로, 경쟁률은 사상 최고치입니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, same navy + gold briefing-series palette, headline "경쟁률" at the top, a sharply rising line graph dominating the canvas with bright accent dots at each inflection point, small subtitle "사상 최고치", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '경쟁률 사상 최고' },
        { sceneNumber: 5, duration: '3', layout: 'full', noTextOverlay: true,
          narration: '다음 브리핑에서도 꼭 필요한 정보만 정리해드리겠습니다.',
          visualDescription: 'Full-frame avatar back to studio backdrop, warm confident closing expression' },
      ],
      cta: '구독하고 다음 1퍼센트 인사이트도 받아보세요.',
    },
  },
  {
    id: 'dongwan_secret',
    label: '훈남 제자의 수행평가 치트키',
    summary: '학생부·면접·공부 치트키를 동완쌤에게 전수받은 비법으로 풀어주는 형',
    direction: [
      '남자 제자 아바타를 영상 내내 풀샷으로 유지. PIP·인포그래픽·차트로 전환 금지.',
      '배경은 따뜻한 조명의 아늑한 방 — 책상에 앉거나 소파에 기대거나 창가에 서서 말하는 등 편안한 자세.',
      '한 영상 안에서는 같은 공간만 사용. 씬마다 카메라 앵글·자세만 바꿔 변화 — 정면 미디엄샷 → 살짝 사이드 → 클로즈업 → 다시 풀샷.',
      '말투는 동생에게 알려주듯 친근·구어체. "이거 동완쌤한테 직접 배운 건데~" 식의 설정 환기를 매 씬 자연스럽게.',
      '편집은 빠른 컷 전환과 강한 키워드 자막(2~3단어). 트렌디한 쇼츠 영상미.',
      '저장·공유를 자연스럽게 유도하는 CTA로 마무리.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.male_student],
    // 표준 엔드포인트(/v2/video/generate)로 렌더한다 — Video Agent 자동 연출 미사용.
    // 솔로 + 전 씬 순수 아바타라 canMergeSoloTake 가 발동해 나레이션 전체를
    // video_input 1개로 병합 → 컷 없는 연속 테이크. 자막은 이후 씬별 번인.
    useStandardEndpoint: true,
    // 컨셉 가이드: "한 영상 안에서는 같은 공간만 사용" + 영상마다 분위기 변화.
    // → randomVariantPerVideo: true 로 영상 1개당 1개 variant 를 랜덤 픽 후 모든 씬에 동일 적용.
    // 풀은 "아늑한 방" 가이드와 잘 맞는 실내 variant 중 9:16 세로 룩 5개.
    // ※ 9:16 세로 룩만 등록 — 16:9 가로 룩은 쇼츠(9:16) 프레이밍이 깨지므로 추가 금지.
    sceneAvatarIds: [
      '98514c36beb94007a1ab493d583cf5c6', // 의자 컵, 모던 거실 라운지
      'f3db5b47238c4a4ba58885d24a3f1faa', // 창가 제스처, 회색 맨투맨
      '726a2f45007c41da89f4fde587796ece', // 스튜디오 정면, 차콜 셔츠
      '440f2af83f58425ab54a3f163a7dfd52', // 실내 정면샷, 차콜 카라 셔츠
      'f55a98c799b84d859469982014ab9e3c', // 모던 오피스, 차콜 반팔 셔츠
    ],
    randomVariantPerVideo: true,
    testScript: {
      title: '동완쌤 전수 수행평가 치트키 3',
      duration: '15',
      hook: '수행평가 치트키, 동완쌤한테 배운 거 그대로 풀어줄게.',
      scenes: [
        { sceneNumber: 1, duration: '4',
          narration: '얘들아, 수행 주제 정할 때 동완쌤이 알려준 비법이 있어.',
          visualDescription: 'Male student sitting casually at a warm-lit wooden desk, leaning slightly toward camera, friendly medium shot, cozy bedroom-style background with soft bokeh, chest-up framing',
          textOverlay: '동완쌤 비법 시작' },
        { sceneNumber: 2, duration: '4',
          narration: '주제는 무조건 "내 경험 + 사회 키워드" 로 묶어. 그래야 평가자가 기억해.',
          visualDescription: 'Same male student now sitting on a soft beige sofa in the same cozy room, holding a notebook loosely, slight side angle, relaxed posture, same warm lighting and room continuity',
          textOverlay: '경험 + 키워드' },
        { sceneNumber: 3, duration: '4',
          narration: '발표는 첫 문장에 결론을 박아. 동완쌤이 항상 강조하는 거야.',
          visualDescription: 'Close-up of the same male student in the same room speaking with confident smile, gesturing with one hand, soft window light from the side, same cozy room mood',
          textOverlay: '첫 문장에 결론' },
        { sceneNumber: 4, duration: '3',
          narration: '이 두 개만 챙겨도 수행 점수 확 올라가. 저장해 두고 써먹어.',
          visualDescription: 'Same male student back to medium shot at the same desk, leaning back slightly with a satisfied smile, soft thumbs-up gesture, same warm lighting and room continuity',
          textOverlay: '저장 필수' },
      ],
      cta: '도움 됐으면 친구한테도 공유 ㄱㄱ.',
    },
  },
  {
    id: 'godsaeng_routine',
    label: '미녀 제자 상위 0.1퍼센트 갓생 루틴',
    summary: '시각적으로 아름다운 공부 환경 + AI 플래너 활용 브이로그',
    direction: [
      '여자 제자 아바타를 영상 내내 풀화면 유지. PIP·차트·자막 박스 등 그래픽 요소는 최소화.',
      '한 영상 안에서는 같은 공간만 사용 — 아바타 variant 자체에 포함된 배경을 그대로 쓰고, 별도 배경 합성(Gemini 등)은 하지 않는다. 영상마다 다른 variant 가 랜덤 선택돼 분위기가 달라진다.',
      '깔끔한 데스크테리어, 미학적 영상미, 따뜻한 자연광이 일관된 톤.',
      '말투는 친근하고 조곤조곤한 브이로그 톤. 나레이션은 특정 시간대(새벽·저녁)에 묶지 말 것 — 어떤 공간 variant 가 깔려도 자연스럽도록 공부 루틴·팁 중심으로 작성.',
      '청소년 팬덤 형성과 시각 만족 우선.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.female_student],
    // 표준 엔드포인트(/v2/video/generate)로 렌더한다 — Video Agent 자동 연출 미사용.
    // 솔로 + 전 씬 순수 아바타라 canMergeSoloTake 가 발동해 컷 없는 연속 테이크로 렌더.
    useStandardEndpoint: true,
    // 컨셉 가이드: "한 영상 안에서는 같은 공간만 사용" (dongwan_secret 과 동일 방식).
    // → randomVariantPerVideo: true 로 영상 1개당 Alexa variant 1개를 랜덤 픽해 모든 씬에 동일 적용.
    // 별도 배경 합성은 쓰지 않는다 — variant 자체 배경을 그대로 사용해 합성 어색함을 없앤다.
    // 풀은 Alexa variant 중 9:16 세로 룩 5개.
    // ※ 9:16 세로 룩만 등록 — 16:9 가로 룩은 쇼츠(9:16) 프레이밍이 깨지므로 추가 금지.
    sceneAvatarIds: [
      '62b02a920a78424e94f63f2ddb85dc99', // 창가 미소, 흰 홀터넥 + 헤어밴드
      '62bc0097e3ec4154bd8133e73c6ff12d', // 창가 침실, 핑크 니트
      '057d99ff22cc47a9be6d5773cb46e2e0', // 거실 셀카, 검정 테두리 가디건
      '7e16d04300e74074bc77e7c0bfb97e87', // 복도 셀카, 베이지 니트 + 하늘색 셔츠
      '7a9c3518725e4f788b61df77e7d36c34', // 창가 복도, 흰 홀터넥 + 베이지 가디건
    ],
    randomVariantPerVideo: true,
    testScript: {
      title: '상위 0.1퍼센트 갓생 루틴',
      duration: '15',
      hook: '상위 0.1퍼센트의 갓생 루틴, 공개할게요.',
      scenes: [
        { sceneNumber: 1, duration: '4',
          narration: '하루를 시작할 때 AI 플래너로 목표 세 개를 정해요.',
          visualDescription: 'Female student avatar in a cozy study space, friendly medium shot, relaxed welcoming posture, chest-up framing',
          textOverlay: '목표 3개' },
        { sceneNumber: 2, duration: '4',
          narration: '50분 몰입, 10분 휴식 사이클로 돌려요.',
          visualDescription: 'Same female student, slight side angle, calm focused expression, same space continuity, chest-up framing',
          textOverlay: '50분 + 10분' },
        { sceneNumber: 3, duration: '4',
          narration: '배운 내용은 음성으로 녹음해서 복습해요.',
          visualDescription: 'Close-up of the same female student speaking softly with a gentle gesture, same warm space continuity, chest-up framing',
          textOverlay: '복습은 음성으로' },
        { sceneNumber: 4, duration: '3',
          narration: '루틴이 나를 만든다는 거, 진짜예요.',
          visualDescription: 'Same female student back to a medium shot with a warm reassuring smile, same space continuity, chest-up framing',
          textOverlay: '루틴 = 나' },
      ],
      cta: '저만의 갓생 꿀팁, 댓글로 더 알려드릴게요.',
    },
  },
  {
    id: 'pet_dictionary',
    label: '입시 강아지의 30초 용어 사전',
    summary: '귀여운 강아지가 학생들에게 입시 용어를 친절하게 풀어주는 시리즈',
    direction: [
      '안경 쓴 강아지 아바타를 인트로(첫 씬)·아웃트로(마지막 씬)·예시 씬에서 풀샷으로 유지해 캐릭터성을 확립. PIP·다른 인물 컷은 금지.',
      '중간 씬 중 수치·데이터 또는 강조 키워드(예: 용어 정의, 수치 분류) 가 핵심인 부분은 풀화면 인포그래픽으로 전환 — HeyGen AI 가 visualDescription 으로부터 생성한 인포그래픽이 화면을 채우고, 아바타는 노출하지 않으며 강아지 보이스오버로 진행.',
      '인포그래픽은 친근한 학생 브이로그 톤 — 채도 낮은 따뜻한 책상 톤(베이지·크림·연한 우드)과 플레이풀한 한글 키워드. 차트·아이콘은 부드럽게 처리해 위협적이지 않게.',
      '아바타 씬 배경은 따뜻한 조명의 같은 아늑한 책상. 한 영상 안에서는 같은 공간만 사용하고, 씬마다 카메라 앵글·자세만 살짝 변화 (정면 → 살짝 사이드 → 클로즈업 → 다시 정면).',
      '시청 타깃은 학생. 또래 친구가 알려주듯 친근한 반말 톤이지만, "쪽팔려", "망해", "손해 봐" 같은 위협·자극 표현은 절대 금지. "같이 알아보자", "처음엔 다 헷갈려", "내가 쉽게 풀어줄게" 같은 공감·도움 베이스로만 진행.',
      '한 영상에 용어 1개를 깊게 다룸. 구조: 공감 훅(아바타) → 정의·데이터(인포그래픽) → 친절한 꿀팁(아바타 또는 인포그래픽) → 예시(아바타) → 따뜻한 한 줄 마무리(아바타).',
      '강아지 캐릭터이지만 대사·나레이션에 "멍" 같은 의성어 추임새는 절대 넣지 않는다 — 음성으로 들으면 어색하므로 캐릭터성은 비주얼(안경 쓴 강아지 아바타)로만 표현. 자막은 2~3 단어 키워드로 짧고 굵게.',
      'CTA는 강요 없이 부드럽게 — 친구한테 도움될 만한 영상으로 공유 유도, 다음 용어 신청 댓글 유도.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.dog_student],
    // 인포그래픽 씬을 HeyGen 자체 AI 가 직접 그리도록 Video Agent (/v1/video_agent/generate) 경로 사용.
    // 표준 엔드포인트($1/분) 대신 $2/분 — 자연어 프롬프트로 인포그래픽 시각화·아바타 미노출 등 직접 지시.
    testScript: {
      title: '수시 6장 같이 알아보자',
      duration: '15',
      hook: '수시 6장, 처음엔 어떻게 나눠야 할지 막막하지?',
      scenes: [
        { sceneNumber: 1, duration: '2',
          narration: '수시 6장, 처음엔 어떻게 나눠야 할지 막막하지?',
          visualDescription: 'Cute dog with round glasses sitting at a warm-lit wooden desk, cozy bookshelf background with soft bokeh, friendly chest-up framing, gentle welcoming expression',
          textOverlay: '수시 6장' },
        { sceneNumber: 2, duration: '3', layout: 'infographic-full',
          narration: '수시는 학교를 여섯 번 지원할 수 있어.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, no dog visible, no people, vertical 9:16, warm cozy desk-side palette (soft beige and cream with light wood accents), playful student-vlog infographic style, headline "수시" at the top, a large bold "6" centered as the hero number with a small "장" superscript and a friendly Korean note "학교 6번 지원" beside it, a row of six small rounded school-document icons arranged below the number, soft natural lighting feel, minimal and friendly, no logos',
          textOverlay: '학교 6번 지원' },
        { sceneNumber: 3, duration: '5', layout: 'infographic-full',
          narration: '보통 1지망 두 개, 적정 두 개, 안정 두 개로 나누면 마음이 편해.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, no dog visible, no people, vertical 9:16, same warm cozy desk-side palette (beige and cream with light wood), three equally weighted vertical columns side by side with playful Korean labels "1지망", "적정", "안정" on top of each column and a soft "2" displayed under each label, rounded friendly column shapes in muted warm tones, minimal student-vlog infographic style, no logos',
          textOverlay: '1지망·적정·안정' },
        { sceneNumber: 4, duration: '3',
          narration: '예를 들면 가고 싶은 학교랑 합격 가능성 높은 학교를 섞는 거야.',
          visualDescription: 'Same dog back to friendly chest-up shot at the same desk, soft encouraging smile, same warm room continuity',
          textOverlay: '섞어서 지원' },
        { sceneNumber: 5, duration: '2',
          narration: '오늘은 이거 하나만 기억하면 돼.',
          visualDescription: 'Same dog wagging tail gently, warm closing expression, same cozy desk and lighting',
          textOverlay: '이거 하나만!' },
      ],
      cta: '다음 용어 궁금하면 댓글에 적어줘!',
    },
  },
  {
    id: 'study_dialogue',
    label: '남녀 제자 공부 스타일 영상 통화',
    summary: '두 제자가 영상 통화로 공부 스타일 차이·학습 전략을 수다 떨며 풀어줌',
    direction: [
      '남자 제자·여자 제자가 영상 통화로 공부 스타일을 수다 떠는 컨셉. 한 화면에 한 명씩 — 영상 통화에서 말하는 사람이 풀화면으로 잡히는 느낌.',
      '두 사람은 각자 다른 장소(아바타 자체 배경)에 있다 — 영상 통화이므로 배경이 서로 달라도 자연스럽다.',
      '두 아바타 모두 같은 9:16 프레임에 동일한 방식으로 — 한쪽이 흰 여백으로 채워지면 다른 쪽도 동일하게 — 영상 통화 타일처럼 프레이밍을 통일한다 (backgroundColor 로 흰 배경 통일).',
      '말투는 친한 친구끼리 영상 통화하는 가벼운 수다체. "야 영상 통화 됐다", "요즘 공부 어떻게 해?" 같은 통화 시작·반응 표현 자연스럽게.',
      '대화 흐름: 통화 시작 인사 → 첫 발화자가 자기 공부법 → 상대가 자기 방식 응답 → 차이 공감 → 마지막에 시청자에게 댓글 유도.',
      '자극·비교·우열 표현 금지. 공감·존중 톤. 자막은 2~3 단어 키워드.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.male_student,
      HEYGEN_AVATAR_IDS.female_student,
    ],
    // 영상 통화 컨셉: 두 아바타가 각자 배경에 있되, 프레이밍을 통일하기 위해
    // 모든 씬에 흰색 배경을 깐다 (아바타가 9:16 을 못 채우면 흰 여백으로 일관 처리).
    backgroundColor: '#FFFFFF',
    // 씬 전환은 크로스페이드(디졸브) 대신 단순 컷 — 영상 통화 컨셉이라 컷 전환이 자연스럽다.
    sceneTransition: 'cut',
    testScript: {
      title: '영상 통화로 푸는 공부 스타일',
      duration: '15',
      hook: '친구랑 영상 통화하면서 공부법 비교해봤어.',
      scenes: [
        { sceneNumber: 1, duration: '4',
          narration: '야, 영상 통화 됐다! 요즘 시험 준비 어떻게 해? 나는 25분 집중하고 5분 쉬어.',
          visualDescription: 'Male student facing camera as if on a video call, friendly relaxed expression, chest-up framing',
          textOverlay: '25 + 5 사이클' },
        { sceneNumber: 2, duration: '4',
          narration: '오, 난 좀 달라. 한 번 시작하면 1시간 몰입하고 15분 쉬는 게 더 잘 맞더라.',
          visualDescription: 'Female student facing camera as if on a video call, warm thoughtful smile, chest-up framing',
          textOverlay: '1시간 몰입형' },
        { sceneNumber: 3, duration: '4',
          narration: '오, 너는 길게 가는 게 잘 맞는구나. 사람마다 진짜 다르네.',
          visualDescription: 'Male student facing camera as if on a video call, engaged friendly listener expression, chest-up framing',
          textOverlay: '서로 다른 스타일' },
        { sceneNumber: 4, duration: '3',
          narration: '맞아. 여러분은 어떻게 공부하는지 댓글로 알려주세요.',
          visualDescription: 'Female student facing camera as if on a video call, warm inviting smile and gentle gesture toward camera, chest-up framing',
          textOverlay: '댓글로 알려줘' },
      ],
      cta: '여러분의 공부 스타일도 댓글로 공유해주세요.',
    },
  },
  {
    id: 'parent_mental_care',
    label: '후라이쌤의 학부모 멘탈 케어',
    summary: '학부모의 불안을 위로하며 입시 정보를 따뜻하게 풀어주는 토크',
    direction: [
      '후라이쌤 아바타를 영상 내내 풀샷으로 유지. PIP·차트·다른 인물 컷 금지.',
      '별도 배경 합성은 하지 않는다 — 후라이쌤 아바타의 자체 배경을 그대로 사용. 씬마다 카메라 앵글·자세만 살짝 변화 (정면 미디엄샷 → 살짝 사이드 → 클로즈업 → 다시 정면).',
      '시청 타깃은 입시생 자녀를 둔 어머님. 강사 톤(가르침·지시)이 아닌 "마음 알아주는 따뜻한 어른" 포지션. "어머님, 오늘도 정말 고생 많으셨죠?" 같은 동료 어른 말투.',
      '핵심 결은 "위로 → 입시 시스템 정보". 학부모의 불안을 먼저 인정·위로한 뒤, 그 불안을 덜어줄 시스템·일정·행동 가이드를 따뜻하게 전달 → 정보가 위로의 형태로 전달되는 구조.',
      '"이거 모르면 자녀 손해 봐요" 같은 위협·자극 표현 절대 금지. 데이터·수치·정책 분석은 동완쌤(briefing_dongwan) 영역이므로, 같은 정보도 "그러니 어머님은 이렇게 하시면 돼요" 식의 학부모 행동 가이드로 번역.',
      'CTA는 강요 없이 부드럽게 — 주변 어머님께 살짝 전해주세요 정도. 맘카페·학부모 단톡방 공유를 자연스럽게 유도.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.fry_ssaem],
    // 표준 엔드포인트(/v2/video/generate)로 렌더한다 — Video Agent 자동 연출 미사용.
    // 솔로 + 전 씬 순수 아바타라 canMergeSoloTake 가 발동해 컷 없는 연속 테이크로 렌더.
    useStandardEndpoint: true,
    testScript: {
      title: '수능 D-100, 어머님은 이것만 기억하세요',
      duration: '15',
      hook: '수능 D-100, 어머님이 더 떨리시죠?',
      scenes: [
        { sceneNumber: 1, duration: '3',
          narration: '수능 D-100, 어머님이 더 떨리시죠?',
          visualDescription: 'Warm Korean middle-aged woman avatar, gentle compassionate expression, chest-up framing',
          textOverlay: 'D-100' },
        { sceneNumber: 2, duration: '2',
          narration: '그 마음, 정말 이해해요.',
          visualDescription: 'Same woman, slight side angle, soft empathetic smile, hands gently folded, chest-up framing',
          textOverlay: '그 마음 이해해요' },
        { sceneNumber: 3, duration: '4',
          narration: '잔소리 대신 "오늘 하루도 수고했어" 한 마디만 해주세요.',
          visualDescription: 'Close-up of the same woman speaking warmly with a gentle hand gesture',
          textOverlay: '한 마디면 충분' },
        { sceneNumber: 4, duration: '3',
          narration: '도시락에 응원 쪽지 한 줄, 효과 정말 큽니다.',
          visualDescription: 'Same woman back to chest-up shot, warm reassuring smile',
          textOverlay: '응원 쪽지 한 줄' },
        { sceneNumber: 5, duration: '3',
          narration: '어머님이 평온해야 아이도 안정돼요.',
          visualDescription: 'Same woman, soft warm closing expression, gentle nodding, chest-up framing',
          textOverlay: '엄마의 평온' },
      ],
      cta: '주변 어머님께도 살짝 전해주세요.',
    },
  },
  {
    id: 'ox_quiz',
    label: '전 인물 총출동 입시 상식 OX 퀴즈',
    summary: '다섯 인물이 같은 무대에서 번갈아 등장해 OX 퀴즈를 내고 즉시 정답을 풀어주는 시리즈',
    // UI 선택 목록에서 임시로 숨김 — 코드·테스트 스크립트에서는 계속 동작. 노출 여부는 추후 결정.
    hiddenFromUI: true,
    direction: [
      '5명 (동완쌤·후라이쌤·남자 제자·여자 제자·강아지 제자) 이 한 영상에서 모두 등장.',
      '모든 씬은 동일한 단색 배경(backgroundColor) 위에 올라간다 — 5명이 같은 무대에 선 듯한 일관성. 별도 배경 이미지 합성은 하지 않는다.',
      '한 화면에 1명씩만 등장 (HeyGen 제약). 카메라 정면, 중앙 배치, 풀샷 유지.',
      '각 문제는 3개 씬으로 구성한다: ① 질문 씬(인물이 OX 문제 제시) → ② quiz-countdown 대기 씬(같은 인물이 3초간 말 없이 대기, 3·2·1 카운트다운 영상이 배경) → ③ 정답 씬(같은 인물이 정답·해설). 한 문제의 3개 씬은 반드시 같은 인물(avatarId)로 고정.',
      '말투는 친근한 쇼호스트 톤. 강아지 제자도 대사·나레이션에 "멍" 같은 의성어 추임새는 넣지 않는다 (음성으로 들으면 어색). 위협·자극 표현 금지, 댓글 유도형 마무리.',
      '자막은 짧게 — 질문 씬은 Q번호만 노출(정답 스포일 금지), 정답 씬에서 Q번호+정답 공개. 빠른 컷 전환 + 중독성 있는 효과음 느낌.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.dongwan_ssaem,
      HEYGEN_AVATAR_IDS.fry_ssaem,
      HEYGEN_AVATAR_IDS.male_student,
      HEYGEN_AVATAR_IDS.female_student,
      HEYGEN_AVATAR_IDS.dog_student,
    ],
    // 5명을 동일 단색 배경 위에 올려 같은 무대에 선 듯한 일관성을 준다 (Gemini 합성 미사용).
    // quiz-countdown 대기 씬은 카운트다운 영상 배경이 우선하므로 단색이 적용되지 않는다.
    backgroundColor: '#1A2D4A',
    testScript: {
      title: '입시 OX 퀴즈 5문제',
      duration: '45',
      hook: '3초 안에 답할 수 있어? OX 퀴즈 시작!',
      // 각 문제 = 질문 씬 → quiz-countdown 대기 씬(3초 침묵 + 카운트다운 배경 영상) → 정답 씬.
      // 한 문제의 3개 씬은 같은 avatarId 로 묶어 같은 인물이 묻고·기다리고·답한다.
      scenes: [
        // Q1 — 동완쌤
        { sceneNumber: 1, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: 'OX 퀴즈 시작! 내신등급은 절대평가다. O일까, X일까?',
          visualDescription: 'Dongwan teacher center stage as MC posing the quiz question, confident warm smile, chest-up framing',
          textOverlay: 'Q1' },
        { sceneNumber: 2, duration: '3', layout: 'quiz-countdown', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '',
          visualDescription: 'Dongwan teacher waiting calmly for viewers to answer, relaxed idle pose, chest-up framing',
          textOverlay: '' },
        { sceneNumber: 3, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '정답은 X! 내신은 상대평가예요.',
          visualDescription: 'Dongwan teacher revealing the answer with a confident gesture, chest-up framing',
          textOverlay: 'Q1 · 정답 X' },
        // Q2 — 후라이쌤
        { sceneNumber: 4, duration: '3', avatarId: HEYGEN_AVATAR_IDS.fry_ssaem,
          narration: '수능 최저는 모든 대학에 적용된다. O일까, X일까?',
          visualDescription: 'Frysaem in the same quiz studio posing the question, playful friendly expression, chest-up framing',
          textOverlay: 'Q2' },
        { sceneNumber: 5, duration: '3', layout: 'quiz-countdown', avatarId: HEYGEN_AVATAR_IDS.fry_ssaem,
          narration: '',
          visualDescription: 'Frysaem waiting playfully for the answer, idle pose, chest-up framing',
          textOverlay: '' },
        { sceneNumber: 6, duration: '3', avatarId: HEYGEN_AVATAR_IDS.fry_ssaem,
          narration: '정답은 X! 대학마다 달라요.',
          visualDescription: 'Frysaem revealing the answer with a warm friendly expression, chest-up framing',
          textOverlay: 'Q2 · 정답 X' },
        // Q3 — 남자 제자
        { sceneNumber: 7, duration: '3', avatarId: HEYGEN_AVATAR_IDS.male_student,
          narration: '학종은 면접만 본다. O일까, X일까?',
          visualDescription: 'Male student in the same quiz studio posing the question, energetic friendly tone, chest-up framing',
          textOverlay: 'Q3' },
        { sceneNumber: 8, duration: '3', layout: 'quiz-countdown', avatarId: HEYGEN_AVATAR_IDS.male_student,
          narration: '',
          visualDescription: 'Male student waiting for viewers to answer, idle pose, chest-up framing',
          textOverlay: '' },
        { sceneNumber: 9, duration: '3', avatarId: HEYGEN_AVATAR_IDS.male_student,
          narration: '정답은 X! 서류도 같이 봐.',
          visualDescription: 'Male student revealing the answer with a friendly gesture, chest-up framing',
          textOverlay: 'Q3 · 정답 X' },
        // Q4 — 여자 제자
        { sceneNumber: 10, duration: '3', avatarId: HEYGEN_AVATAR_IDS.female_student,
          narration: '논술은 정시 전형이다. O일까, X일까?',
          visualDescription: 'Female student in the same quiz studio posing the question, bright cheerful expression, chest-up framing',
          textOverlay: 'Q4' },
        { sceneNumber: 11, duration: '3', layout: 'quiz-countdown', avatarId: HEYGEN_AVATAR_IDS.female_student,
          narration: '',
          visualDescription: 'Female student waiting for viewers to answer, idle pose, chest-up framing',
          textOverlay: '' },
        { sceneNumber: 12, duration: '3', avatarId: HEYGEN_AVATAR_IDS.female_student,
          narration: '정답은 X! 논술은 수시에 속해요.',
          visualDescription: 'Female student revealing the answer with a cheerful gesture, chest-up framing',
          textOverlay: 'Q4 · 정답 X' },
        // Q5 — 강아지 제자
        { sceneNumber: 13, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dog_student,
          narration: '특목고는 무조건 유리하다! O일까, X일까?',
          visualDescription: 'Cute dog student in the same quiz studio posing the question, wagging tail, friendly tone, chest-up framing',
          textOverlay: 'Q5' },
        { sceneNumber: 14, duration: '3', layout: 'quiz-countdown', avatarId: HEYGEN_AVATAR_IDS.dog_student,
          narration: '',
          visualDescription: 'Cute dog student waiting for viewers to answer, idle pose, chest-up framing',
          textOverlay: '' },
        { sceneNumber: 15, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dog_student,
          narration: '정답은 X! 본인 노력이 더 중요해.',
          visualDescription: 'Cute dog student revealing the answer with a happy tail wag, chest-up framing',
          textOverlay: 'Q5 · 정답 X' },
      ],
      cta: '몇 개 맞췄어? 댓글에 적어줘, 다음 편에서 또 풀어줄게!',
    },
  },
  {
    id: 'mock_interview',
    label: '동완쌤 면접 답변 클리닉',
    summary: '동완쌤이 제자의 면접 답변 예시를 보여주고 좋은 점·보완점을 짚어주는 클리닉 시리즈',
    direction: [
      '동완쌤(면접 코치) 과 제자(면접 답변 예시) 가 등장. 한 화면에 1명씩만 (HeyGen 제약).',
      '동완쌤은 면접 답변을 평가·코칭하는 역할 — 인트로·평가·마무리 씬에 등장. 제자는 "면접 답변 예시 영상" 역할 — 답변하는 씬에만 등장.',
      '제자의 답변 씬은 동완쌤이 리뷰하는 "예시 영상" 컨셉이라, 제자 배경이 동완쌤과 달라도 자연스럽다 (별도 영상을 틀어주는 셈). 그 씬 자막에 "면접 답변 예시" 류로 클립임을 표시.',
      '동완쌤은 단정한 정장 + 차분한 코치 톤. 제자는 단정한 셔츠 + 면접 응시 자세.',
      '구조: ① 동완쌤 인트로(면접 답변 알려준다) → ② 제자 면접 답변 예시 → ③·④ 동완쌤이 좋은 점·보완점 평가 → ⑤ 동완쌤 마무리 + 댓글 유도.',
      '평가는 "좋은 점 → 보완점" 순으로 균형있게. 보완점도 "이렇게 하면 더 좋아진다" 식 격려 톤. 위협·자극 표현 금지.',
      '시리즈 시그너처는 비주얼·인트로 일관성으로만 — EP 번호·회차 자막 절대 금지. 자막은 2~3 단어 키워드.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.dongwan_ssaem,
      HEYGEN_AVATAR_IDS.interview_student,
    ],
    // 동완쌤(코치) ↔ 제자(답변 예시 영상) 교차. 각 씬 avatarId 명시로 역할 배정 고정.
    // 동완쌤 씬은 모두 같은 아바타라 배경이 일관되고, 제자 답변 씬은 "예시 영상" 이라
    // 배경이 달라도 자연스럽다 — 그래서 backgroundColor(단색 강제)는 쓰지 않는다.
    // 씬 전환은 크로스페이드(디졸브) 대신 단순 컷.
    sceneTransition: 'cut',
    testScript: {
      title: '면접 답변 클리닉 — 지원동기 편',
      duration: '17',
      hook: '이 면접 답변, 합격할 수 있을까요?',
      // 배정: 씬1 동완쌤 인트로 → 씬2 제자 답변 예시 → 씬3·4 동완쌤 평가 → 씬5 동완쌤 마무리.
      scenes: [
        { sceneNumber: 1, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '면접 답변, 합격하는 답엔 공식이 있어요. 실제 예시로 짚어드릴게요.',
          visualDescription: 'Dongwan teacher in a clean dark navy suit, confident friendly coach expression, chest-up framing',
          textOverlay: '면접 답변 클리닉' },
        { sceneNumber: 2, duration: '4', avatarId: HEYGEN_AVATAR_IDS.interview_student,
          narration: '저는 어릴 때부터 의사가 멋있어 보여서 의대에 지원했습니다.',
          visualDescription: 'Female student in a neat white blouse answering an interview question, composed candidate posture, chest-up framing',
          textOverlay: '면접 답변 예시' },
        { sceneNumber: 3, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '좋은 점은 솔직하고 간결하다는 거예요.',
          visualDescription: 'Dongwan teacher giving an encouraging nod with a warm coaching expression, chest-up framing',
          textOverlay: '좋은 점 · 솔직함' },
        { sceneNumber: 4, duration: '4', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '보완점은 "왜" 가 약하다는 거예요. 구체적인 경험을 한 가지만 넣어도 훨씬 설득력 있어요.',
          visualDescription: 'Dongwan teacher sharing an insight with a gentle hand gesture, chest-up framing',
          textOverlay: '보완 · 구체적 경험' },
        { sceneNumber: 5, duration: '3', avatarId: HEYGEN_AVATAR_IDS.dongwan_ssaem,
          narration: '여러분이라면 어떻게 답할래요? 댓글로 남겨주세요.',
          visualDescription: 'Dongwan teacher in a warm closing chest-up shot, slight inviting gesture toward camera',
          textOverlay: '댓글로 알려줘' },
      ],
      cta: '여러분의 지원동기 답변, 댓글로 적어주세요.',
    },
  },
]

export const SHORTS_VIDEO_CONCEPT_OPTIONS = [
  { value: '', label: '컨셉을 선택하지 않음' },
  // hiddenFromUI: true 인 컨셉은 선택 드롭다운에서 제외한다 (코드·테스트에서는 계속 동작).
  ...SHORTS_VIDEO_CONCEPTS
    .filter((concept) => !concept.hiddenFromUI)
    .map(({ id, label }) => ({ value: id, label })),
]

export function findShortsVideoConcept(id) {
  if (!id) return null
  return SHORTS_VIDEO_CONCEPTS.find((concept) => concept.id === id) || null
}

export function buildShortsConceptExtra(conceptId) {
  const concept = findShortsVideoConcept(conceptId)
  if (!concept) return ''
  return [
    `컨셉: ${concept.label}`,
    `요약: ${concept.summary}`,
    `연출 방향: ${concept.direction}`,
  ].join('\n')
}
