// 쇼츠 영상 10가지 컨셉 프리셋.
// 사용자가 컨셉을 고르면 영상 추가 지시(extra)에 컨셉 설명이 자동 반영되고,
// 가능한 경우 어울리는 프리셋 아바타도 추천한다.
// preferredAvatarIds 가 1개면 솔로 컨셉, 2개 이상이면 멀티 아바타 컨셉.
// useStandardEndpoint: true 이면 솔로여도 /v2/video/generate 로 만든다 ($1/분, 자동 연출 X).
// sceneAvatarIds (선택): 같은 인물의 HeyGen Photo Avatar variant 들을 씬마다 순환시킨다.
//   - 솔로 컨셉(preferredAvatarIds 1개) 위에 얹는 옵션이라 useMultiAvatar 분기는 타지 않는다.
//   - 씬 수가 배열 길이보다 많으면 mod 순환.
//   - 정의되지 않으면 preferredAvatarIds[0] 만 사용 (기존 동작).
// randomVariantPerVideo (선택, sceneAvatarIds 와 함께만 의미 있음):
//   - true 면 영상 1개를 만들 때 sceneAvatarIds 중 1개를 랜덤으로 뽑아 모든 씬에 동일 적용한다.
//     → 한 영상 안에서는 같은 배경, 영상마다 배경이 달라짐 (dongwan_secret 처럼 "같은 방" 가이드용).
//   - false/생략이면 기본 동작(씬마다 mod 순환).
// shuffleSceneVariants (선택, sceneAvatarIds 와 함께만 의미 있음):
//   - true 면 영상 1개를 만들 때마다 sceneAvatarIds 풀을 랜덤 셔플해 씬마다 서로 다른 variant 를 쓴다.
//     → 같은 인물의 여러 룩이 한 영상에서 순환, 영상마다 룩 조합이 달라짐 (godsaeng_routine 브이로그 흐름용).
//   - randomVariantPerVideo 와 동시에 true 면 randomVariantPerVideo 가 우선한다.
// testScript 는 컨셉 테스트용 약 15초 분량 대본.
// 아바타 ID 는 heygenAvatars.js 의 단일 진실 소스(HEYGEN_AVATAR_IDS) 에서만 참조한다.
// (단 sceneAvatarIds 는 같은 인물의 variant 라 raw 문자열로 작성한다.)

import { HEYGEN_AVATAR_IDS } from './heygenAvatars'

export const SHORTS_VIDEO_CONCEPTS = [
  {
    id: 'briefing_dongwan',
    label: '동완쌤 1퍼센트 입시 데이터 브리핑',
    summary: '공신력 있는 통계로 입시 정책 변화를 분석',
    direction: [
      '신뢰감 있는 정장 차림과 전문적인 말투. 채널 권위 강화에 초점.',
      '인트로(씬 1) · 아웃트로(마지막 씬) 는 동완쌤 풀화면.',
      '중간 데이터 씬은 HeyGen AI 가 생성하는 풀화면 인포그래픽 화면으로 전환 — 아바타는 화면에 노출하지 않고 보이스오버만 깔린다. 차트·숫자·키워드 같은 시각 요소는 우리가 따로 그리지 않고 HeyGen 의 장면 생성에 맡긴다 (visualDescription 으로 지시).',
      'PIP·좌상단 작은 아바타 합성 금지.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.dongwan_ssaem],
    useStandardEndpoint: true,
    testScript: {
      title: '의대 선호도 1퍼센트의 진실',
      duration: '15',
      hook: '의대 입시의 비밀, 데이터로 보여드립니다.',
      scenes: [
        { sceneNumber: 1, duration: '3', layout: 'full',
          narration: '안녕하세요, 동완쌤입니다. 오늘은 의대 입시 데이터를 풀어드릴게요.',
          visualDescription: 'Full-frame avatar in a clean studio with navy backdrop and subtle gold accent',
          textOverlay: '동완쌤 1퍼센트 브리핑' },
        { sceneNumber: 2, duration: '3', layout: 'infographic-full',
          narration: '의대 선호도가 작년 대비 12.4퍼센트 상승했습니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, navy backdrop with subtle gold accent matching the briefing series, headline "의대 선호도" at the top, a large bold "+12.4%" centered as the hero statistic, a clean ascending bar chart below the number, small subtitle "작년 대비 상승", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '의대 선호도 +12.4%' },
        { sceneNumber: 3, duration: '3', layout: 'infographic-full',
          narration: '상위 1퍼센트 중 절반이 의대를 선택합니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, same navy + gold briefing-series palette, headline "상위 1%" at the top, a large bold "50%" centered as the hero statistic, a clean pie chart split exactly in half below the number, small subtitle "의대 선택", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '상위 1% 중 의대 50%' },
        { sceneNumber: 4, duration: '3', layout: 'infographic-full',
          narration: '정원은 그대로, 경쟁률은 사상 최고치입니다.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, vertical 9:16, same navy + gold briefing-series palette, headline "경쟁률" at the top, a sharply rising line graph dominating the canvas with bright accent dots at each inflection point, small subtitle "사상 최고치", minimal Korean broadcast-news infographic style, no logos',
          textOverlay: '경쟁률 사상 최고' },
        { sceneNumber: 5, duration: '3', layout: 'full',
          narration: '다음 브리핑에서도 꼭 필요한 정보만 정리해드리겠습니다.',
          visualDescription: 'Full-frame avatar back to studio backdrop, warm confident closing expression',
          textOverlay: '다음 브리핑에서 만나요' },
      ],
      cta: '구독하고 다음 1퍼센트 인사이트도 받아보세요.',
    },
  },
  {
    id: 'dongwan_secret',
    label: '훈남 제자의 수행평가 치트키',
    summary: '학생부·면접·공부 치트키를 동완쌤에게 전수받은 비법으로 풀어주는 형',
    direction: [
      '남자 제자 아바타를 영상 내내 풀샷으로 유지. PIP·인포그래픽·차트로 전환 금지.',
      '배경은 따뜻한 조명의 아늑한 방 — 책상에 앉거나 소파에 기대거나 창가에 서서 말하는 등 편안한 자세.',
      '한 영상 안에서는 같은 공간만 사용. 씬마다 카메라 앵글·자세만 바꿔 변화 — 정면 미디엄샷 → 살짝 사이드 → 클로즈업 → 다시 풀샷.',
      '말투는 동생에게 알려주듯 친근·구어체. "이거 동완쌤한테 직접 배운 건데~" 식의 설정 환기를 매 씬 자연스럽게.',
      '편집은 빠른 컷 전환과 강한 키워드 자막(2~3단어). 트렌디한 쇼츠 영상미.',
      '저장·공유를 자연스럽게 유도하는 CTA로 마무리.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.male_student],
    // 컨셉 가이드: "한 영상 안에서는 같은 공간만 사용" + 영상마다 분위기 변화.
    // → randomVariantPerVideo: true 로 영상 1개당 1개 variant 를 랜덤 픽 후 모든 씬에 동일 적용.
    // 풀은 "아늑한 방" 가이드와 잘 맞는 실내 variant 7종 (정확 4 + 보더라인 3).
    // 기본 male_student (해변 선베드) 같은 야외/해변 variant 는 의도적으로 제외.
    sceneAvatarIds: [
      // 정확 매칭 (아늑한 방·거실·창가)
      '0893ea6525994226a96b654cd729b742', // 창가 소파 앉음, 회색 맨투맨, 컵
      '0d67157b8c3c40a3b381dc60d0f2614e', // 거실 정면, 회색 라운드넥 티셔츠
      '98514c36beb94007a1ab493d583cf5c6', // 의자 컵, 모던 거실 라운지
      'f3db5b47238c4a4ba58885d24a3f1faa', // 창가 제스처, 회색 맨투맨
      // 보더라인 (실내지만 톤이 살짝 formal)
      '726a2f45007c41da89f4fde587796ece', // 스튜디오 정면, 차콜 셔츠
      '440f2af83f58425ab54a3f163a7dfd52', // 실내 정면샷, 차콜 카라 셔츠
      'f55a98c799b84d859469982014ab9e3c', // 모던 오피스, 차콜 반팔 셔츠
    ],
    randomVariantPerVideo: true,
    useStandardEndpoint: true,
    testScript: {
      title: '동완쌤 전수 수행평가 치트키 3',
      duration: '15',
      hook: '수행평가 치트키, 동완쌤한테 배운 거 그대로 풀어줄게.',
      scenes: [
        { sceneNumber: 1, duration: '4',
          narration: '얘들아, 수행 주제 정할 때 동완쌤이 알려준 비법이 있어.',
          visualDescription: 'Male student sitting casually at a warm-lit wooden desk, leaning slightly toward camera, friendly medium shot, cozy bedroom-style background with soft bokeh, chest-up framing',
          textOverlay: '동완쌤 비법 시작' },
        { sceneNumber: 2, duration: '4',
          narration: '주제는 무조건 "내 경험 + 사회 키워드" 로 묶어. 그래야 평가자가 기억해.',
          visualDescription: 'Same male student now sitting on a soft beige sofa in the same cozy room, holding a notebook loosely, slight side angle, relaxed posture, same warm lighting and room continuity',
          textOverlay: '경험 + 키워드' },
        { sceneNumber: 3, duration: '4',
          narration: '발표는 첫 문장에 결론을 박아. 동완쌤이 항상 강조하는 거야.',
          visualDescription: 'Close-up of the same male student in the same room speaking with confident smile, gesturing with one hand, soft window light from the side, same cozy room mood',
          textOverlay: '첫 문장에 결론' },
        { sceneNumber: 4, duration: '3',
          narration: '이 두 개만 챙겨도 수행 점수 확 올라가. 저장해 두고 써먹어.',
          visualDescription: 'Same male student back to medium shot at the same desk, leaning back slightly with a satisfied smile, soft thumbs-up gesture, same warm lighting and room continuity',
          textOverlay: '저장 필수' },
      ],
      cta: '도움 됐으면 친구한테도 공유 ㄱㄱ.',
    },
  },
  {
    id: 'godsaeng_routine',
    label: '미녀 제자 상위 0.1퍼센트 갓생 루틴',
    summary: '시각적으로 아름다운 공부 환경 + AI 플래너 활용 브이로그',
    direction: [
      '여자 제자 아바타를 영상 내내 풀화면 유지. PIP·차트·자막 박스 등 그래픽 요소는 최소화.',
      '씬마다 배경 장소가 바뀌는 브이로그 흐름: 새벽 침실 → 공부 책상 → 카페·거실 → 저녁 책상.',
      '깔끔한 데스크테리어, 미학적 영상미, 따뜻한 자연광이 일관된 톤.',
      '컷 전환은 빠르고 매끄럽게. 같은 인물이 다른 장소에서 이어 말하는 느낌.',
      '말투는 친근하고 조곤조곤한 브이로그 톤. 청소년 팬덤 형성과 시각 만족 우선.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.female_student],
    // 컨셉 가이드: 씬마다 배경 장소가 바뀌는 브이로그 흐름 — 영상마다 룩 조합 다양화.
    // 같은 인물 "Alexa" 12 variant 전부를 풀에 넣고 shuffleSceneVariants 로
    // 영상 생성 시마다 셔플해 씬마다 다른 룩을 뽑는다 (영상마다 다른 4가지 룩 조합).
    sceneAvatarIds: [
      '62b02a920a78424e94f63f2ddb85dc99', // 창가 미소, 흰 홀터넥 + 헤어밴드
      '62bc0097e3ec4154bd8133e73c6ff12d', // 창가 침실, 핑크 니트
      'a5454d8b999d4e5f87f486605465aae4', // 창가 가디건, 베이지 (기본 변형)
      '10e2042ed6b04649af6421221795e75c', // 야외 카페, 크림 니트 + 청바지
      '8813a91ea46847cd80baffbaa5f2b17e', // 카페 앉음, 베이지 니트 + 컵
      '04e3819affbe42f3ba0b8df2688f1576', // 거실 소파 앉음, 크림 가디건
      'd4a53ea25a724aacb252c5e6f273b6e4', // 계단 앉음, 베이지 가디건
      '057d99ff22cc47a9be6d5773cb46e2e0', // 거실 셀카, 검정 테두리 가디건
      'dac36601dd9447a7a41d88b37dbac8d6', // 창가 복도 인사, 베이지 + 블루 셔츠
      '539574131395485aac85c015c72cecb0', // 거실 소파 미소, 검정 카라 베이지 가디건
      '7e16d04300e74074bc77e7c0bfb97e87', // 복도 셀카, 베이지 니트 + 하늘색 셔츠
      '7a9c3518725e4f788b61df77e7d36c34', // 창가 복도, 흰 홀터넥 + 베이지 가디건
    ],
    shuffleSceneVariants: true,
    useStandardEndpoint: true,
    testScript: {
      title: '상위 0.1퍼센트 갓생 루틴',
      duration: '15',
      hook: '오늘도 5시 30분, 갓생 시작.',
      scenes: [
        { sceneNumber: 1, duration: '4', layout: 'full-vlog',
          narration: '기상하자마자 AI 플래너로 목표 세 개를 정해요.',
          visualDescription: 'Aesthetic Korean teenage bedroom in early dawn, soft warm morning sunlight streaming through linen curtains, neatly made bed with cream beddings, minimal wooden desk with an AI planner tablet glowing softly, dried flowers in a small vase, study-with-me vlog aesthetic, calm and elegant atmosphere',
          textOverlay: '5:30 AM · 목표 3개' },
        { sceneNumber: 2, duration: '4', layout: 'full-vlog',
          narration: '50분 몰입, 10분 휴식 사이클로 돌려요.',
          visualDescription: 'Cozy minimalist study desk in mid-morning, wooden surface, open notebook with neat handwriting, lo-fi pomodoro timer display, ceramic coffee mug, small green plant, soft natural side light, focused study vlog aesthetic, no people visible',
          textOverlay: '50분 + 10분' },
        { sceneNumber: 3, duration: '4', layout: 'full-vlog',
          narration: '배운 내용은 음성으로 녹음해서 복습해요.',
          visualDescription: 'Sunlit quiet cafe corner in afternoon, warm wooden tones, a frothy latte and a smartphone resting on a notebook, voice memo waveform on screen, blurred soft bokeh background, Korean cafe vlog aesthetic, peaceful and warm mood',
          textOverlay: '복습은 음성으로' },
        { sceneNumber: 4, duration: '3', layout: 'full-vlog',
          narration: '루틴이 나를 만든다는 거, 진짜예요.',
          visualDescription: 'Evening study desk with a warm orange lamp glow, open leather journal with handwritten notes, a cup of tea, soft dim lighting, closing vlog scene aesthetic, calm reflective atmosphere',
          textOverlay: '루틴 = 나' },
      ],
      cta: '저만의 갓생 꿀팁, 댓글로 더 알려드릴게요.',
    },
  },
  {
    id: 'pet_dictionary',
    label: '입시 강아지의 30초 용어 사전',
    summary: '귀여운 강아지가 학생들에게 입시 용어를 친절하게 풀어주는 시리즈',
    direction: [
      '안경 쓴 강아지 아바타를 인트로(첫 씬)·아웃트로(마지막 씬)·예시 씬에서 풀샷으로 유지해 캐릭터성을 확립. PIP·다른 인물 컷은 금지.',
      '중간 씬 중 수치·데이터 또는 강조 키워드(예: 용어 정의, 수치 분류) 가 핵심인 부분은 풀화면 인포그래픽으로 전환 — HeyGen AI 가 visualDescription 으로부터 생성한 인포그래픽이 화면을 채우고, 아바타는 노출하지 않으며 강아지 보이스오버(+"멍" 추임새) 로 진행.',
      '인포그래픽은 친근한 학생 브이로그 톤 — 채도 낮은 따뜻한 책상 톤(베이지·크림·연한 우드)과 플레이풀한 한글 키워드. 차트·아이콘은 부드럽게 처리해 위협적이지 않게.',
      '아바타 씬 배경은 따뜻한 조명의 같은 아늑한 책상. 한 영상 안에서는 같은 공간만 사용하고, 씬마다 카메라 앵글·자세만 살짝 변화 (정면 → 살짝 사이드 → 클로즈업 → 다시 정면).',
      '시청 타깃은 학생. 또래 친구가 알려주듯 친근한 반말 톤이지만, "쪽팔려", "망해", "손해 봐" 같은 위협·자극 표현은 절대 금지. "같이 알아보자", "처음엔 다 헷갈려", "내가 쉽게 풀어줄게" 같은 공감·도움 베이스로만 진행.',
      '한 영상에 용어 1개를 깊게 다룸. 구조: 공감 훅(아바타) → 정의·데이터(인포그래픽) → 친절한 꿀팁(아바타 또는 인포그래픽) → 예시(아바타) → 따뜻한 한 줄 마무리(아바타).',
      '강아지 캐릭터성을 위해 매 씬 또는 마무리에 "멍" 추임새 자연스럽게 — 인포그래픽 씬에서도 보이스오버에 "멍" 포함. 자막은 2~3 단어 키워드로 짧고 굵게.',
      'CTA는 강요 없이 부드럽게 — 친구한테 도움될 만한 영상으로 공유 유도, 다음 용어 신청 댓글 유도.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.dog_student],
    useStandardEndpoint: true,
    testScript: {
      title: '수시 6장 같이 알아보자 (멍)',
      duration: '15',
      hook: '수시 6장, 처음엔 어떻게 나눠야 할지 막막하지? 멍',
      scenes: [
        { sceneNumber: 1, duration: '2',
          narration: '수시 6장, 처음엔 어떻게 나눠야 할지 막막하지? 멍.',
          visualDescription: 'Cute dog with round glasses sitting at a warm-lit wooden desk, cozy bookshelf background with soft bokeh, friendly chest-up framing, gentle welcoming expression',
          textOverlay: '수시 6장' },
        { sceneNumber: 2, duration: '3', layout: 'infographic-full',
          narration: '수시는 학교를 여섯 번 지원할 수 있어, 멍.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, no dog visible, no people, vertical 9:16, warm cozy desk-side palette (soft beige and cream with light wood accents), playful student-vlog infographic style, headline "수시" at the top, a large bold "6" centered as the hero number with a small "장" superscript and a friendly Korean note "학교 6번 지원" beside it, a row of six small rounded school-document icons arranged below the number, soft natural lighting feel, minimal and friendly, no logos',
          textOverlay: '학교 6번 지원' },
        { sceneNumber: 3, duration: '5', layout: 'infographic-full',
          narration: '보통 1지망 두 개, 적정 두 개, 안정 두 개로 나누면 마음이 편해, 멍.',
          visualDescription: 'Full-frame data infographic generated by HeyGen, no avatar visible, no dog visible, no people, vertical 9:16, same warm cozy desk-side palette (beige and cream with light wood), three equally weighted vertical columns side by side with playful Korean labels "1지망", "적정", "안정" on top of each column and a soft "2" displayed under each label, rounded friendly column shapes in muted warm tones, minimal student-vlog infographic style, no logos',
          textOverlay: '1지망·적정·안정' },
        { sceneNumber: 4, duration: '3',
          narration: '예를 들면 가고 싶은 학교랑 합격 가능성 높은 학교를 섞는 거야, 멍.',
          visualDescription: 'Same dog back to friendly chest-up shot at the same desk, soft encouraging smile, same warm room continuity',
          textOverlay: '섞어서 지원' },
        { sceneNumber: 5, duration: '2',
          narration: '오늘은 이거 하나만 기억하면 돼, 멍.',
          visualDescription: 'Same dog wagging tail gently, warm closing expression, same cozy desk and lighting',
          textOverlay: '이거 하나만!' },
      ],
      cta: '다음 용어 궁금하면 댓글에 적어줘, 멍!',
    },
  },
  {
    id: 'study_dialogue',
    label: '남녀 제자 공부 스타일 토크',
    summary: '두 제자가 같은 공간에서 번갈아 대화하며 공부 스타일 차이·학습 전략을 풀어줌',
    direction: [
      '남자 제자·여자 제자가 번갈아 등장. 한 화면에 한 명씩만 보임 (HeyGen 제약).',
      '같은 영상 안에서는 같은 배경 1장을 공유 (sharedBackground) — 카페·스터디룸·도서관 같은 친근한 공간. 매 영상 생성 시 Gemini 가 새 분위기로 다시 만듦.',
      '씬마다 한 명씩 카메라 정면. speakerSide 가 left 면 화면 좌측에 배치(offset.x = -0.30), right 면 우측(offset.x = +0.30). 같은 공간에 마주 앉아 대화하는 느낌.',
      '대화 흐름: 첫 발화자가 자기 고민·방법 공유 → 상대가 자기 방식 응답 → 차이 정리 → 마지막 발화자가 시청자에게 댓글 유도.',
      '말투는 친근한 또래 대화체. 자극·비교·우열 표현 금지. "나는 이렇게 해, 너는 어때?" "오, 너는 그렇게 하는구나" 같은 공감·존중 톤.',
      '자막은 2~3 단어 키워드. CTA 는 마지막 씬에 자연스럽게.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.male_student,
      HEYGEN_AVATAR_IDS.female_student,
    ],
    testScript: {
      title: '나의 공부 스타일, 너는 어때?',
      duration: '15',
      hook: '요즘 공부, 어떻게 하고 있어?',
      sharedBackground: {
        visualDescription: 'Cozy bright Korean study cafe with warm wood tones, two empty seats facing camera with a shared wooden table, soft window light, indoor plants, no people, peaceful study vlog aesthetic, vertical 9:16',
      },
      scenes: [
        { sceneNumber: 1, duration: '4', layout: 'dialogue-shared-bg', speakerSide: 'left',
          narration: '요즘 시험 준비 중인데, 나는 25분 집중하고 5분 쉬는 식으로 가고 있어. 너는 어때?',
          visualDescription: 'Male student facing camera on left side of a shared study cafe seat, friendly relaxed expression, chest-up framing',
          textOverlay: '25 + 5 사이클' },
        { sceneNumber: 2, duration: '4', layout: 'dialogue-shared-bg', speakerSide: 'right',
          narration: '난 좀 달라. 한 번 시작하면 1시간 몰입하고 15분 쉬는 게 더 잘 맞더라.',
          visualDescription: 'Female student facing camera on right side of the same study cafe seat, warm thoughtful smile, chest-up framing',
          textOverlay: '1시간 몰입형' },
        { sceneNumber: 3, duration: '4', layout: 'dialogue-shared-bg', speakerSide: 'left',
          narration: '오, 너는 길게 가는 게 잘 맞는구나. 사람마다 진짜 다르네.',
          visualDescription: 'Male student leaning slightly forward in the same shared cafe space, engaged listener expression, chest-up framing',
          textOverlay: '서로 다른 스타일' },
        { sceneNumber: 4, duration: '3', layout: 'dialogue-shared-bg', speakerSide: 'right',
          narration: '여러분들은 어떻게 하고 있는지 댓글에 남겨주세요.',
          visualDescription: 'Female student facing camera on right side with warm inviting smile and gentle gesture toward camera, chest-up framing',
          textOverlay: '댓글로 알려줘' },
      ],
      cta: '서로 다른 공부 스타일, 댓글로 공유해주세요.',
    },
  },
  {
    id: 'parent_mental_care',
    label: '후라이쌤의 학부모 멘탈 케어',
    summary: '학부모의 불안을 위로하며 입시 정보를 따뜻하게 풀어주는 토크',
    direction: [
      '후라이쌤 아바타를 영상 내내 풀샷으로 유지. PIP·차트·다른 인물 컷 금지.',
      '배경은 따뜻한 조명의 거실 또는 창가. 한 영상 안에서는 같은 공간만 사용하고, 씬마다 카메라 앵글·자세만 살짝 변화 (정면 미디엄샷 → 살짝 사이드 → 클로즈업 → 다시 정면).',
      '배경에 반려견이 졸고 있거나 옆에 앉아있는 모습이 자연스럽게 비치도록 — 힐링감을 위한 보조 요소.',
      '시청 타깃은 입시생 자녀를 둔 어머님. 강사 톤(가르침·지시)이 아닌 "마음 알아주는 따뜻한 어른" 포지션. "어머님, 오늘도 정말 고생 많으셨죠?" 같은 동료 어른 말투.',
      '핵심 결은 "위로 → 입시 시스템 정보". 학부모의 불안을 먼저 인정·위로한 뒤, 그 불안을 덜어줄 시스템·일정·행동 가이드를 따뜻하게 전달 → 정보가 위로의 형태로 전달되는 구조.',
      '"이거 모르면 자녀 손해 봐요" 같은 위협·자극 표현 절대 금지. 데이터·수치·정책 분석은 동완쌤(briefing_dongwan) 영역이므로, 같은 정보도 "그러니 어머님은 이렇게 하시면 돼요" 식의 학부모 행동 가이드로 번역.',
      'CTA는 강요 없이 부드럽게 — 주변 어머님께 살짝 전해주세요 정도. 맘카페·학부모 단톡방 공유를 자연스럽게 유도.',
    ].join(' '),
    preferredAvatarIds: [HEYGEN_AVATAR_IDS.fry_ssaem],
    useStandardEndpoint: true,
    testScript: {
      title: '수능 D-100, 어머님은 이것만 기억하세요',
      duration: '15',
      hook: '수능 D-100, 어머님이 더 떨리시죠?',
      scenes: [
        { sceneNumber: 1, duration: '3',
          narration: '수능 D-100, 어머님이 더 떨리시죠?',
          visualDescription: 'Warm Korean middle-aged woman avatar sitting on a soft beige sofa in a cozy living room, warm evening lamp glow, a small dog napping peacefully on a cushion beside her, gentle compassionate expression, chest-up framing',
          textOverlay: 'D-100' },
        { sceneNumber: 2, duration: '2',
          narration: '그 마음, 정말 이해해요.',
          visualDescription: 'Same woman in the same cozy living room, slight side angle, soft empathetic smile, hands gently folded, same warm lamp lighting and room continuity, dog still resting nearby',
          textOverlay: '그 마음 이해해요' },
        { sceneNumber: 3, duration: '4',
          narration: '잔소리 대신 "오늘 하루도 수고했어" 한 마디만 해주세요.',
          visualDescription: 'Close-up of the same woman speaking warmly with a gentle hand gesture, same warm living room lighting, same cozy room mood',
          textOverlay: '한 마디면 충분' },
        { sceneNumber: 4, duration: '3',
          narration: '도시락에 응원 쪽지 한 줄, 효과 정말 큽니다.',
          visualDescription: 'Same woman back to chest-up shot on the same sofa, warm reassuring smile, same warm room continuity, dog still resting peacefully beside her',
          textOverlay: '응원 쪽지 한 줄' },
        { sceneNumber: 5, duration: '3',
          narration: '어머님이 평온해야 아이도 안정돼요.',
          visualDescription: 'Same woman in soft warm closing expression on the same sofa, gentle nodding, dog curled up beside her, warm cozy living room mood',
          textOverlay: '엄마의 평온' },
      ],
      cta: '주변 어머님께도 살짝 전해주세요.',
    },
  },
  {
    id: 'ox_quiz',
    label: '전 인물 총출동 입시 상식 OX 퀴즈',
    summary: '다섯 인물이 같은 무대에서 번갈아 등장해 OX 퀴즈를 내고 즉시 정답을 풀어주는 시리즈',
    direction: [
      '5명 (동완쌤·후라이쌤·남자 제자·여자 제자·강아지 제자) 이 한 영상에서 모두 등장.',
      '같은 영상 안에서는 같은 배경 1장 공유 (sharedBackground) — 퀴즈쇼 무대 느낌. 매 영상 생성 시 Gemini 가 새 분위기로 다시 만듦.',
      '한 화면에 1명씩만 등장 (HeyGen 제약). 카메라 정면, 중앙 배치, 풀샷 유지.',
      '씬마다 다른 인물이 차례로 퀴즈를 내고 곧바로 정답까지 짧게 풀어줌 (Q + A 한 씬 안에). 3초 안에 마무리.',
      '말투는 친근한 쇼호스트 톤. 강아지는 "멍" 추임새 자연스럽게. 위협·자극 표현 금지, 댓글 유도형 마무리.',
      '자막은 2~3 단어 키워드 (Q번호 + 정답). 빠른 컷 전환 + 중독성 있는 효과음 느낌.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.dongwan_ssaem,
      HEYGEN_AVATAR_IDS.fry_ssaem,
      HEYGEN_AVATAR_IDS.male_student,
      HEYGEN_AVATAR_IDS.female_student,
      HEYGEN_AVATAR_IDS.dog_student,
    ],
    testScript: {
      title: '입시 OX 퀴즈 5문제',
      duration: '15',
      hook: '3초 안에 답할 수 있어? OX 퀴즈 시작!',
      sharedBackground: {
        visualDescription: 'Vibrant Korean quiz show studio stage with soft pastel lighting, a clean rounded podium, friendly bright atmosphere, vertical 9:16 composition, no people visible, no text overlays, no logos',
      },
      scenes: [
        { sceneNumber: 1, duration: '3', layout: 'quiz-shared-bg',
          narration: 'OX 퀴즈 시작! 내신등급은 절대평가다. 정답은 X. 상대평가예요.',
          visualDescription: 'Dongwan teacher center stage as MC opening the quiz, confident warm smile, chest-up framing',
          textOverlay: 'Q1 · 정답 X' },
        { sceneNumber: 2, duration: '3', layout: 'quiz-shared-bg',
          narration: '수능 최저는 모든 대학에 적용된다. 정답은 X. 대학마다 달라잉.',
          visualDescription: 'Frysaem in the same quiz studio, playful friendly expression, chest-up framing',
          textOverlay: 'Q2 · 정답 X' },
        { sceneNumber: 3, duration: '3', layout: 'quiz-shared-bg',
          narration: '학종은 면접만 본다. 정답은 X. 서류도 같이 봐.',
          visualDescription: 'Male student in the same quiz studio, energetic friendly tone, chest-up framing',
          textOverlay: 'Q3 · 정답 X' },
        { sceneNumber: 4, duration: '3', layout: 'quiz-shared-bg',
          narration: '논술은 정시 전형이다. 정답은 X. 수시에 속해요.',
          visualDescription: 'Female student in the same quiz studio, bright cheerful expression, chest-up framing',
          textOverlay: 'Q4 · 정답 X' },
        { sceneNumber: 5, duration: '3', layout: 'quiz-shared-bg',
          narration: '특목고는 무조건 유리하다. 멍! 정답은 X. 본인 노력이 더 중요해.',
          visualDescription: 'Cute dog student in the same quiz studio wagging tail, friendly closing tone, chest-up framing',
          textOverlay: 'Q5 · 정답 X' },
      ],
      cta: '몇 개 맞췄어? 댓글에 적어줘, 다음 편에서 또 풀어줄게!',
    },
  },
  {
    id: 'mock_interview',
    label: 'AI 가상 인물 미래 대입 면접 미리보기',
    summary: '동완쌤이 AI 면접관 역할로 빈출 질문을 묻고, 제자가 학과 맞춤형으로 답해주는 면접 시뮬레이션 시리즈',
    direction: [
      '두 아바타(동완쌤 면접관 + 제자 응시자) 가 등장하되, 한 화면에 1명씩만 비치도록 1인 교차 컷으로 진행 — 같은 프레임에 두 명을 합성하지 말 것 (HeyGen 제약).',
      '면접관 컷 ↔ 응시자 컷이 교대로 나오며, 두 사람 모두 같은 면접실 공간에 있는 것처럼 visualDescription 에 "same interview room continuity" 를 매 씬 명시.',
      '동완쌤은 단정한 정장 + 차분한 면접관 톤, 제자는 단정한 셔츠 + 살짝 긴장한 응시자 자세로 대조 명확하게.',
      '시리즈 시그너처는 비주얼·인트로 일관성으로만 표현 — EP 번호·회차·Q1·Q2 같은 자막 절대 금지. 시청자가 썸네일·오프닝만 보고 "어 이 시리즈" 알아보게.',
      '매 영상 첫 씬은 동완쌤 면접관 컷에서 "AI 면접관한테 모의 면접 해봤어." 류 시그너처 인트로 한 마디로 시작 → 시리즈 정체성.',
      '응시자 자기소개는 영상 주제(학과) 에 맞춰 매번 다르게: "저는 의대 입시를 준비하는 ○○입니다" / "저는 공대 입시를 준비하는 ○○입니다" 식. 학과 키워드가 영상 주제를 자연스럽게 드러냄.',
      '구조: 메타 훅 → 면접 질문 → 응시자 답변 → 동완쌤 인사이트 한 줄 → 호기심 갭 CTA. 답을 끝까지 다 공개하지 않고 "여러분이라면? 댓글로" 식으로 댓글 유도.',
      '위협·자극 표현 금지. AI 활용 역량 시연으로 채널 정체성을 강화하는 메타 메시지를 첫 씬 인트로에 자연스럽게 녹임.',
    ].join(' '),
    preferredAvatarIds: [
      HEYGEN_AVATAR_IDS.dongwan_ssaem,
      HEYGEN_AVATAR_IDS.female_student,
    ],
    testScript: {
      title: 'AI 면접관 모의 면접 — 의대 자기소개 편',
      duration: '15',
      hook: 'AI 면접관한테 의대 모의 면접 해봤어.',
      scenes: [
        { sceneNumber: 1, duration: '2',
          narration: 'AI 면접관한테 모의 면접 해봤어.',
          visualDescription: 'Dongwan teacher avatar in a clean dark navy suit, sitting upright in a calm modern interview room with soft neutral lighting and a subtle wood-panel background, chest-up framing, confident professional expression, same interview room continuity',
          textOverlay: 'AI 모의 면접' },
        { sceneNumber: 2, duration: '3',
          narration: '본인을 한 문장으로 소개해주세요.',
          visualDescription: 'Dongwan teacher in the same interview room, slight forward lean toward camera as if asking the candidate, calm interviewer tone, same neutral lighting and same wood-panel background, chest-up framing, same interview room continuity',
          textOverlay: '자기소개' },
        { sceneNumber: 3, duration: '3',
          narration: '저는 의대 입시를 준비하는 OOO입니다.',
          visualDescription: 'Female student avatar in a neat white blouse seated across from the interviewer in the same interview room, slightly nervous but composed candidate posture, hands folded on the desk, same neutral lighting and same wood-panel background continuity, chest-up framing',
          textOverlay: '의대 입시 준비' },
        { sceneNumber: 4, duration: '3',
          narration: '정체성과 학과 키워드를 한 문장에 묶는 게 첫 인상 비결이야.',
          visualDescription: 'Dongwan teacher back to chest-up shot in the same interview room, gentle confident smile sharing an insight, same neutral lighting and same wood-panel background continuity',
          textOverlay: '한 문장에 묶기' },
        { sceneNumber: 5, duration: '4',
          narration: '여러분이라면 한 문장으로 어떻게 소개할래? 댓글에 적어줘.',
          visualDescription: 'Dongwan teacher in warm closing chest-up shot in the same interview room, slight inviting gesture toward camera, same neutral lighting and same wood-panel background continuity',
          textOverlay: '댓글로 알려줘' },
      ],
      cta: '여러분의 한 문장 자기소개, 댓글에 적어줘.',
    },
  },
]

export const SHORTS_VIDEO_CONCEPT_OPTIONS = [
  { value: '', label: '컨셉을 선택하지 않음' },
  ...SHORTS_VIDEO_CONCEPTS.map(({ id, label }) => ({ value: id, label })),
]

export function findShortsVideoConcept(id) {
  if (!id) return null
  return SHORTS_VIDEO_CONCEPTS.find((concept) => concept.id === id) || null
}

export function buildShortsConceptExtra(conceptId) {
  const concept = findShortsVideoConcept(conceptId)
  if (!concept) return ''
  return [
    `컨셉: ${concept.label}`,
    `요약: ${concept.summary}`,
    `연출 방향: ${concept.direction}`,
  ].join('\n')
}
